server:
  port: 8000
spring:
  application:
    name: cambio-service
  datasource:
    url: ${DATASOURCE_URL}/cambio_service?useTimezone=true&serverTimezone=UTC
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    url: ${DATASOURCE_URL}/
    schemas: cambio_service
    user: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}


  