server:
  port: 8000

#Spring
spring:
  application:
    name: cambio-service
  datasource:
    url: ${DATASOURCE_URL}/cambio_service?useTimezone=true&serverTimezone=UTC
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  flyway:
    url: ${DATASOURCE_URL}/cambio_service?useTimezone=true&serverTimezone=UTC
    user: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
#Spring Docs
springdoc:
  show-actuator: true
  api-docs:
    path: cambio-service/v3/api-docs
      
#Resilience4j
resilience4j:
  retry:
    instances:
      default:
        max-attempts: 5
        wait-duration: 1s


  