server:
  port: 8100
  
#Spring
spring:
  application:
    name: book-service
  datasource:
    url: ${DATASOURCE_URL}/book_service?useTimezone=true&serverTimezone=UTC
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false            
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    url: ${DATASOURCE_URL}/book_service?useTimezone=true&serverTimezone=UTC
    user: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    
#Spring Docs
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs
    
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

