server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    url: ${DATASOURCE_URL}/book_service?useTimezone=true&serverTimezone=UTC
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    url: ${DATASOURCE_URL}/
    schemas: book_service
    user: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

